FROM python:3.11-slim
WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
RUN uvx pip install --system uv

COPY pyproject.toml uv.lock* ./
COPY judger ./judger
COPY main.py .

RUN uv sync --no-dev

EXPOSE 8000

CMD ["uv", "run", "python", "main.py"]
