FROM python:3.11-slim
WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
RUN uvx pip install --system uv

COPY pyproject.toml .
RUN uv sync --frozen --no-dev

COPY judger ./judger
COPY main.py .

EXPOSE 8000

CMD ["uv", "run", "python", "main.py"]
